name: docker-push

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Lowercase image name
        id: lowercase
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ format('ghcr.io/{0}', github.repository) }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.lowercase.outputs.lowercase }}:latest
            ${{ steps.lowercase.outputs.lowercase }}:${{ github.sha }}
